Tried to save plots, failed
Tried to update the plotting functions so that they would save the plots in graphs folder, but get error in matplotlib.pyplot.savefig:

FileNotFoundError: [Errno 2] No such file or directory: 'graphs/Average proportion of red balls over time.png'

Similar errors for each of 3 instances of savefig in utilities/plot.